version: "3.8"

services:
  backend:
    build: .
    volumes:
      - ./app:/app  # Ensures live code updates
    ports:
      - "8000:8000"  # Adjust for your API port
    environment:
      - ENV=development
    command: []  # Allows overriding the default command