services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./construct:/app/construct
      - ./tests:/app/tests
    environment:
      - ENV=development
      - PYTHONPATH=/app   # so you can import e.g. "import construct.agent"
    command: []