services:
  backend:
    build: .
    ports:
      - "8000:8000"  # Exposes FastAPI
    volumes:
      - ./app:/app  # Enables live reload
    environment:
      - ENV=development
    command: []  # Allows entrypoint.sh to decide what to run